apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-giropops
    app: giropops-strigus
  name: nginx-giropops
spec:
  containers:
  - name: nginx-giropops
    image: nginx
    ports:
    - containerPort: 80
    resources: 
      limits: 
        memory: "5000Mi"
        cpu: "0.5m"
      requests:
        memory: "4400Mi"
        cpu: "0.3m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
